communication:
  mode: 'serial'
  serial:
    baudRate: 38400
  osc:
    listenIp: "0.0.0.0"
    listenPort: 1337
debugMode: True
serialEnabled: True

dmeDevices:
  - name: "test 1"
    id: 1
    mode: "serial"
    serialPort: "/dev/ttySC0"
  - name: "test 2"
    id: 2
    mode: "serial"
    serialPort: "/dev/ttySC1"
    



